version: "3.4"

services:
  scheduler:
    image: diego1q2w/jdk-11-sqlite-alpine
    depends_on:
      - rabbitmq
      - rabbitmq-scheduler-topology
    ports:
      - "7000:7000"
    volumes:
      - build-scheduler-cache:/root/.gradle
      - .:/app
      - /app/.gradle
    environment:
      RABBITMQ_HOSTNAME: amqp://guest:guest@rabbitmq:5672
      SERVICE_NAME: scheduler
      WAIT_FOR_PORTS: rabbitmq:5672
    command: bash -c "wait-for-ports ./gradlew :pleo-antaeus-scheduler:build && ./gradlew :pleo-antaeus-scheduler:run"

  retrier:
    image: diego1q2w/jdk-11-sqlite-alpine
    depends_on:
      - rabbitmq
      - rabbitmq-retrier-topology
    ports:
      - "7001:7000"
    volumes:
      - build-retrier-cache:/root/.gradle
      - .:/app
      - /app/.gradle
    environment:
      RABBITMQ_HOSTNAME: amqp://guest:guest@rabbitmq:5672
      SERVICE_NAME: retrier
      WAIT_FOR_PORTS: rabbitmq:5672
    command: bash -c "wait-for-ports ./gradlew :pleo-antaeus-retrier:build && ./gradlew :pleo-antaeus-retrier:run"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
    logging:
      driver: none

  rabbitmq-scheduler-topology:
    image: diego1q2w/setup-events-topology
    depends_on:
      - rabbitmq
    volumes:
      - ./pleo-antaeus-scheduler/src/main/resources/topology:/setup-events-topology/topology
    environment:
      RABBITMQ_HOSTNAME: amqp://guest:guest@rabbitmq:5672/
      SERVICE_NAME: scheduler # This is the group name of consumers or buckets
      WAIT_FOR_PORTS: rabbitmq:5672

  rabbitmq-retrier-topology:
    image: diego1q2w/setup-events-topology
    depends_on:
      - rabbitmq
    volumes:
      - ./pleo-antaeus-retrier/src/main/resources/topology:/setup-events-topology/topology
    environment:
      RABBITMQ_HOSTNAME: amqp://guest:guest@rabbitmq:5672/
      SERVICE_NAME: retrier # This is the group name of consumers or buckets
      WAIT_FOR_PORTS: rabbitmq:5672

volumes:
  build-scheduler-cache:
  build-retrier-cache: